import { Types } from "mongoose";
import { Gender, Permission, UserRole, UserStatus } from "./enums";
import { IAddress, IAvatar, IMetadata, IPreferences, ILoginHistory } from "./subInterfaces";

export interface IUser {
  username: string;
  email?: string;
  password?: string;
  firstName?: string;
  lastName?: string;
  displayName?: string;
  avatar?: IAvatar;
  phone?: string;
  phoneVerified?: boolean;
  dateOfBirth?: Date;
  gender?: Gender;
  bio?: string;
  website?: string;
  socialLinks?: Record<string, string>;
  status: UserStatus;
  role: UserRole;
  permissions: Permission[];
  isActive: boolean;
  isOnline: boolean;
  isVerified: boolean;
  emailVerified: boolean;
  isBanned: boolean;
  isSuspended: boolean;
  isDeleted: boolean;
  googleId?: string;
  githubId?: string;
  facebookId?: string;
  socketId?: string;
  lastSeen: Date;
  lastLoginDevice?: string;
  userLanguage: string;
  timezone: string;
  registrationIP?: string;
  detectedCountry?: string;
  currentIP?: string;
  followers: Types.ObjectId[];
  following: Types.ObjectId[];
  friends: Types.ObjectId[];
  blockedUsers: Types.ObjectId[];
  friendRequests?: {
    sent: Types.ObjectId[];
    received: Types.ObjectId[];
  };
  loginHistory: ILoginHistory[];
  resetPasswordToken?: string;
  resetPasswordExpires?: Date;
  emailVerificationToken?: string;
  emailVerificationExpires?: Date;
  phoneVerificationToken?: string;
  phoneVerificationExpires?: Date;
  passwordChangedAt?: Date;
  loginAttempts: number;
  lockoutUntil?: Date;
  preferences: IPreferences;
  addresses: IAddress[];
  loginCount: number;
  lastLoginAt?: Date;
  accountCreatedAt: Date;
  metadata: IMetadata;
  subscription?: {
    plan: string;
    status: string;
    expiresAt?: Date;
    features: string[];
  };
  apiKeys?: Array<{
    key: string;
    name: string;
    permissions: string[];
    lastUsed?: Date;
    expiresAt?: Date;
    isActive: boolean;
  }>;
  sessions?: Array<{
    sessionId: string;
    deviceInfo: string;
    ipAddress: string;
    createdAt: Date;
    lastActivity: Date;
    isActive: boolean;
  }>;
  auditLog?: Array<{
    action: string;
    details: Record<string, any>;
    ipAddress?: string;
    userAgent?: string;
    timestamp: Date;
  }>;
  createdAt: Date;
  updatedAt: Date;
}
