export const POPULAR_LANGUAGES = {
    'auto': 'Auto Detect',
    'en': 'English',
    'bn': 'Bengali (বাংলা)',
    'hi': 'Hindi (हिन्दी)',
    'ur': 'Urdu (اردو)',
    'ar': 'Arabic (العربية)',
    'zh-CN': 'Chinese Simplified (中文简体)',
    'zh-TW': 'Chinese Traditional (中文繁體)',
    'es': 'Spanish (Español)',
    'fr': 'French (Français)',
    'de': 'German (Deutsch)',
    'it': 'Italian (Italiano)',
    'pt': 'Portuguese (Português)',
    'ru': 'Russian (Русский)',
    'ja': 'Japanese (日本語)',
    'ko': 'Korean (한국어)',
    'th': 'Thai (ไทย)',
    'vi': 'Vietnamese (Tiếng Việt)',
    'id': 'Indonesian (Bahasa Indonesia)',
    'ms': 'Malay (Bahasa Melayu)',
    'tr': 'Turkish (Türkçe)',
    'fa': 'Persian (فارسی)',
    'ta': 'Tamil (தமிழ்)',
    'te': 'Telugu (తెలుగు)',
    'ml': 'Malayalam (മലയാളം)',
    'kn': 'Kannada (ಕನ್ನಡ)',
    'gu': 'Gujarati (ગુજરાતી)',
    'mr': 'Marathi (मराठी)',
    'pa': 'Punjabi (ਪੰਜਾਬੀ)'
};
